sudo: required

services:
  - docker

language: python
script:
  - python -m pytest -v

branches:
  except:
    - experimental
    - develop

branches:
  only:
    - master

after_success:
  - sh .travis/deploy_dockerhub.sh
